# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Ranker - Node.js CI

on:
  push:
    branches: [ master, dev ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]
    steps:
    - uses: actions/checkout@v2
    - name: Extract branch name
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        echo "##[set-output name=sha_short;]$(echo $(git rev-parse --short HEAD))"
      id: extract_branch
    - name: Set Constants
      id: consts
      run: |
        echo ::set-output name=repo::$(echo ${GITHUB_REPOSITORY})
        echo ::set-output name=sha_short::$(git rev-parse --short HEAD)
        echo ::set-output name=image-name::$(echo quay.io/neinnovationorg/ranker})
        echo ::set-output name=branch::${GITHUB_REF#refs/heads/}
        echo ::set-output name=docker_repo::$(echo /neinnovationorg/ranker) 
    - name: Login to Podman
      id: login
      run:  |
         echo ${{ steps.extract_branch.outputs.branch }}
         echo ${{ steps.extract_branch.outputs.sha_short }}
         podman login quay.io -u ${{ secrets.docker_username }} -p ${{ secrets.docker_password }}
    - name: Build Image using Podman
      run: |
         podman build . -t quay.io/neinnovationorg/ranker:${{ steps.extract_branch.outputs.branch }}
    - name: Push Image to Github Registry
      run: |
          podman push quay.io/neinnovationorg/ranker:${{ steps.extract_branch.outputs.branch }}
    - name: OpenShift Action
      uses: redhat-developer/openshift-actions@v2.0
      with:
        # The URL of the Openshift cluster
        openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
        # JSON with values to connect to the Openshift cluster
        parameters: '{"username": "${{ secrets.OPENSHIFT_USER }}", "acceptUntrustedCerts": "true", "password":"${{ secrets.OPENSHIFT_PASSWORD }}"}'
        # Oc command to be executed
        cmd: |
          'version'
          'project vavtar-services'
          'tag --source=docker quay.io/neinnovationorg/ranker:${{ steps.extract_branch.outputs.branch }} vavtar-services/ranker:${{ steps.extract_branch.outputs.branch }}'
